# Generated by Django 4.1.3 on 2022-11-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Aciglama"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "Tamamlandi"), ("False", "Tamamlanmadi")],
                        default="False",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Tarix"),
                ),
            ],
        ),
    ]
